# fly.toml app configuration file generated for fs-nextjs-todos on 2024-03-21T20:20:11+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fs-nextjs-todos'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
